import { describe, expect, it } from "vitest";
import { buildMissedOppCalibrationPlan } from "./missedOpportunityCalibration";
import type { MissedOpportunitySummary } from "./missedOpportunityAudit";

describe("buildMissedOppCalibrationPlan", () => {
  it("suggests forward/momentum tuning when many misses have low target + daily gain", () => {
    const summary: MissedOpportunitySummary = {
      evaluatedAt: new Date().toISOString(),
      universeN: 50,
      with24hN: 40,
      gainersN: 8,
      detectedN: 2,
      missedN: 4,
      heldGainerN: 1,
      outsideWindowGainerN: 1,
      cdDistantGainerN: 0,
      recallPct: 33.3,
      monitorRecallPct: 33.3,
      monitorMissedN: 4,
      monitorDetectedN: 2,
      watchRecallPct: null,
      watchDetectedN: 0,
      watchMissedN: 0,
      watchGainerN: 0,
      falsePositiveN: 0,
      suggestedN: 2,
      precisionPct: 100,
      missedRows: [
        {
          key: "a",
          ticker: "AAA",
          company: null,
          completionDate: "2026-06-20",
          dailyPct24h: 2.2,
          daysToCd: 12,
          bucket: "missed",
          suggested: false,
          exitDecision: "exit",
          probPct: 52,
          planReturnPct: 0.8,
          matchPct: 72,
          segmentRoiPct: -2.1,
          blockers: ["Low forward target (+0.8%)", "P(plan) below Enter threshold (52%)"],
          inPortfolio: false,
          inMonitorWindow: true,
          inOperationalWindow: true,
          inWatchWindow: false,
        },
        {
          key: "b",
          ticker: "BBB",
          company: null,
          completionDate: "2026-06-22",
          dailyPct24h: 1.8,
          daysToCd: 10,
          bucket: "missed",
          suggested: false,
          exitDecision: "review",
          probPct: 48,
          planReturnPct: 1.1,
          matchPct: 68,
          segmentRoiPct: -1.5,
          blockers: ["Low forward target (+1.1%)"],
          inPortfolio: false,
          inMonitorWindow: true,
          inOperationalWindow: true,
          inWatchWindow: false,
        },
      ],
      detectedRows: [],
      cdDistantRows: [],
      watchRows: [],
      watchMissedRows: [],
      watchDetectedRows: [],
      blockerStats: [],
      chartBars: [],
      pnlAllGainersEur: 0,
      pnlRecommendationsEur: 0,
      pnlFairRecommendationsEur: 0,
      fairRecsPositionN: 0,
    };
    const plan = buildMissedOppCalibrationPlan(summary, "en");
    expect(plan.actions.some((a) => a.id === "relax_fwd_with_momentum")).toBe(true);
  });
});
