# Copy SMTP + mobile URL from VPS into local gitignored file for tester invites on local desktop.
# Usage: powershell -ExecutionPolicy Bypass -File scripts\sync_local_tester_email_env.ps1

param(
    [string]$SshHost = "root@91.99.15.48",
    [string]$RemoteEnv = "/opt/biotech/config/profiles/desktop_web_host.env"
)

$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent $PSScriptRoot
$LocalEnv = Join-Path $Root "config\profiles\desktop_web_host.local.env"
$RemoteTmp = "/tmp/supernova_desktop_web_host.env"

$keys = @(
    "SUPERNOVA_PUBLIC_HOST",
    "SUPERNOVA_MOBILE_PUBLIC_URL",
    "SUPERNOVA_SMTP_HOST",
    "SUPERNOVA_SMTP_PORT",
    "SUPERNOVA_SMTP_USER",
    "SUPERNOVA_SMTP_PASSWORD",
    "SUPERNOVA_SMTP_FROM",
    "SUPERNOVA_SMTP_USE_TLS"
)

Write-Host "[sync] Fetch $RemoteEnv from $SshHost ..." -ForegroundColor Cyan
$partial = Join-Path $env:TEMP "supernova_vps_desktop_web_host.env"
scp "${SshHost}:${RemoteEnv}" $partial | Out-Null
if (-not (Test-Path $partial)) {
    Write-Host "Download failed." -ForegroundColor Red
    exit 1
}

$lines = @(
    "# Generated by scripts/sync_local_tester_email_env.ps1 (gitignored)",
    "# Used by tester_approval_email.py when local API has no SMTP/URL env.",
    ""
)
foreach ($line in Get-Content $partial) {
    $trim = $line.Trim()
    if (-not $trim -or $trim.StartsWith("#")) { continue }
    if ($trim -notmatch "^([^=]+)=") { continue }
    $key = $matches[1]
    if ($keys -contains $key) {
        $lines += $trim
    }
}
Remove-Item $partial -Force -ErrorAction SilentlyContinue

if ($lines.Count -le 3) {
    Write-Host "No matching vars found on VPS." -ForegroundColor Red
    exit 1
}

Set-Content -Path $LocalEnv -Value ($lines -join "`n") -Encoding UTF8
Write-Host "[sync] OK -> $LocalEnv ($($lines.Count - 3) vars)" -ForegroundColor Green
Write-Host "Restart local API (Electron or SuperNova API window) and reload Tester Monitor." -ForegroundColor Yellow
